const STR = {
  ACCESS_DENIED: "Access Denied!",
  ACCOUNTANT: "accountant",
  ADMIN: "admin",
  ASSIGNED: "assigned",
  A_ENTRY: "aEntry",
  A_EXIT: "aExit",
  BUS: "bus",
  BUS_STAFF: "bus-staff",
  CASH: "CASH",
  CHEQUE_OR_DD: "CHEQUE_OR_DD",
  CONDUCTOR: "conductor",
  CUSTOMVALIDATION: "CustomValidation",
  CUR_AYEAR_NOT_SET:
    "Current academic year not set, please set the current academic year!",
  CREDIT: "credit",
  DB_BACKUP_TIME_LAST: "DB_BACKUP_TIME_LAST",
  DRIVER: "driver",
  DEBIT: "debit",
  EMAIL_QUEUE: "email_queue",
  ENTRY: "entry",
  EXIT: "exit",
  EXPENSE: "expense",
  FEE_COLLECTION: "FEE_COLLECTION",
  FIELD_IS_INVALID: "%F% is invalid!",
  FIELD_IS_INVALID_AT_IDX: "%F% is invalid at row: %I%",
  FIELD_MISSING: "%F% is missing!",
  FIELD_IS_REQ: "%F% is required!",
  FIELD_IS_REQ_AT_IDX: "%F% is required at row: %I%",
  INCOME: "income",
  INVALID_CREDENTIALS: "Invalid Credentials!",
  INVALID_ADMNO: "Invalid Admission Number!",
  LIBRARIAN: "librarian",
  M_ENTRY: "mEntry",
  M_EXIT: "mExit",
  ONLINE: "ONLINE",
  OTHERS: "OTHERS",
  PAGE_LIMIT_REACHED: "Page limit reached!",
  PARENT: "parent",
  POS_MACHINE: "pos_machine",
  PUSH_QUEUE: "push_queue",
  RECEPTIONIST: "receptionist",
  RESOURSE_404: "%R% not found",
  RESOURSE_404_ID: "%R% not found: %ID%",
  SCHOOL: "school",
  SPEEDOTRACK_API_404: "Speedotrack API Key Not Found (User: %NAME%)",
  STAFF: "staff",
  STUDENT: "student",
  SUPERADMIN: "superadmin",
  TEACHER: "teacher",
  TEST: "test",
  UNABLE_TO_DEL: "Unable to delete: %A% assigned to %B%!",
  UNASSIGNED: "unassigned",
  UNKNOWN: "unknown",
  URL_404: "URL not found!",
  VALUE_NOT_SUP: "{VALUE} is not supported!",
  VALUE_NOT_SUP_AT_IDX: "%V% is not supported at row: %I%",
  WHATSAPP_QUEUE: "whatsapp_queue",
};

const FUNCTIONS = {
  getFieldIsInvalid: (field) => STR.FIELD_IS_INVALID.replace("%F%", field),
  getFieldIsInvalidAtIdx: (field, idx) =>
    STR.FIELD_IS_INVALID_AT_IDX.replace("%F%", field).replace("%I%", idx),
  getFieldMissing: (field) => STR.FIELD_MISSING.replace("%F%", field),
  getFieldIsReq: (field) => STR.FIELD_IS_REQ.replace("%F%", field),
  getFieldIsReqAtIdx: (field, idx) =>
    STR.FIELD_IS_REQ_AT_IDX.replace("%F%", field).replace("%I%", idx),
  getResourse404: (resource) => STR.RESOURSE_404.replace("%R%", resource),
  getResourse404Id: (resource, id) =>
    STR.RESOURSE_404_ID.replace("%R%", resource).replace("%ID%", id),
  getSpeedotrackAPI404: (username) =>
    STR.SPEEDOTRACK_API_404.replace("%NAME%", username),
  getUnableToDel: (a, b) =>
    STR.UNABLE_TO_DEL.replace("%A%", a).replace("%B%", b),
  getValueNotSup: (val) => STR.VALUE_NOT_SUP.replace("{VALUE}", val),
  getValueNotSupAtIdx: (val, idx) =>
    STR.VALUE_NOT_SUP_AT_IDX.replace("%V%", val).replace("%I%", idx),
};

module.exports = { ...STR, ...FUNCTIONS };
